version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:1.5.5
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apk update && apk add --no-cache bash git openssh

      - run:
          name: Terraform Init
          command: terraform init -input=false

      - run:
          name: Terraform Validate
          command: terraform validate

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan -input=false

      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve tfplan

workflows:
  terraform_deploy:
    jobs:
      - terraform
