version: 2.1
jobs:
  terraform_apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Retrieve AWS Credentials from Secrets Manager
          command: |
            export AWS_ACCESS_KEY_ID=$(aws secretsmanager get-secret-value --secret-id aws_access_key_id --query SecretString --output text)
            export AWS_SECRET_ACCESS_KEY=$(aws secretsmanager get-secret-value --secret-id aws_secret_access_key --query SecretString --output text)
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
