version: 2.1

executors:
  terraform_executor:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo

jobs:
  # Job to initialize Terraform
  terraform_init:
    executor: terraform_executor
    steps:
      - checkout  # Check out the repository
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli
      - run:
          name: Terraform Init
          command: terraform init

  # Job to plan Terraform changes
  terraform_plan:
    executor: terraform_executor
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: terraform plan

  # Job to apply Terraform changes (Deploy infrastructure)
  terraform_apply:
    executor: terraform_executor
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  deploy_infra:
    jobs:
      - terraform_init
      - terraform_plan:
          requires:
            - terraform_init
      - terraform_apply:
          requires:
            - terraform_plan
